.PHONY: clean All

All:
	@echo "----------Building project:[ PCLSerranoVidalPablo - Debug ]----------"
	@cd "PCLSerranoVidalPablo" && "$(MAKE)" -f  "PCLSerranoVidalPablo.mk"
clean:
	@echo "----------Cleaning project:[ PCLSerranoVidalPablo - Debug ]----------"
	@cd "PCLSerranoVidalPablo" && "$(MAKE)" -f  "PCLSerranoVidalPablo.mk" clean
